INSERT  INTO `TERRA_QUOTA_BASE`
(`NAME`,`TYPE`,`VALUE`,`DESCN`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`) 
VALUES 
('REDIS','num',20,NULL,NULL,NULL,NULL,NULL,NULL);

DECLARE @TASK_ID LONG(20),@DETAIL_ID1 LONG(20),@DETAIL_ID2 LONG(20),@DETAIL_ID3 LONG(20),@DETAIL_ID4 LONG(20),@DETAIL_ID5 LONG(20);

INSERT  INTO `WEBPORTAL_TEMPLATE_TASK`
(`NAME`,`TASK_TYPE`,`DESCN`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`) VALUES 
('REDIS_CREATE','REDIS','REDIS服务创建',0,NULL,NULL,NULL,NULL);

SET @TASK_ID=@@IDENTITY;

INSERT  INTO `WEBPORTAL_TEMPLATE_TASK_DETAIL`
(`NAME`,`DESCN`,`BEANNAME`,`TASK_TYPE`,`PARAMS`,`RETRY`,`ASYNC_RETRY`,`VERSION`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`) 
VALUES 
('taskCommonCreateService','通用：服务创建','taskCommonCreateService',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,NULL);

SET @DETAIL_ID1=@@identity;

INSERT  INTO `WEBPORTAL_TEMPLATE_TASK_DETAIL`
(`NAME`,`DESCN`,`BEANNAME`,`TASK_TYPE`,`PARAMS`,`RETRY`,`ASYNC_RETRY`,`VERSION`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`) 
VALUES 
('taskCommonSaveInfoService','通用：保存服务信息，例如实例ID','taskCommonSaveInfoService',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,NULL);

SET @DETAIL_ID2=@@identity;

INSERT  INTO `WEBPORTAL_TEMPLATE_TASK_DETAIL`
(`NAME`,`DESCN`,`BEANNAME`,`TASK_TYPE`,`PARAMS`,`RETRY`,`ASYNC_RETRY`,`VERSION`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`) 
VALUES 
('taskCommonCheckStatusService','通用：查询服务创建状态','taskCommonCheckStatusService',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,NULL);

SET @DETAIL_ID3=@@identity;

INSERT  INTO `WEBPORTAL_TEMPLATE_TASK_DETAIL`
(`NAME`,`DESCN`,`BEANNAME`,`TASK_TYPE`,`PARAMS`,`RETRY`,`ASYNC_RETRY`,`VERSION`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`) 
VALUES 
('taskCommonInvokeService','通用：http地址调用','taskCommonInvokeService',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,NULL);

SET @DETAIL_ID4=@@identity;

INSERT  INTO `WEBPORTAL_TEMPLATE_TASK_DETAIL`
(`NAME`,`DESCN`,`BEANNAME`,`TASK_TYPE`,`PARAMS`,`RETRY`,`ASYNC_RETRY`,`VERSION`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`) 
VALUES 
('taskCommonSendUserEmailService','通用：发送用户邮件','taskCommonSendUserEmailService',NULL,NULL,1,0,NULL,NULL,NULL,NULL,NULL,NULL);

SET @DETAIL_ID5=@@identity;

INSERT  INTO `WEBPORTAL_TEMPLATE_TASK_CHAIN`
(`TASK_ID`,`TASK_DETAIL_ID`,`EXECUTE_ORDER`,`RETRY`,`DELETED`,`CREATE_TIME`,`UPDATE_TIME`,`CREATE_USER`,`UPDATE_USER`,`URL`) 
VALUES 
(@TASK_ID,@DETAIL_ID1,1,1,0,NULL,NULL,NULL,NULL,'http://127.0.0.1:8888/services/redis/create'),
(@TASK_ID,@DETAIL_ID2,2,1,0,NULL,NULL,NULL,NULL,'http://127.0.0.1:8888/services/redis/instance'),
(@TASK_ID,@DETAIL_ID3,3,1,0,NULL,NULL,NULL,NULL,'http://127.0.0.1:8888/services/redis/{id}/status/analyse'),
(@TASK_ID,@DETAIL_ID4,4,1,0,NULL,NULL,NULL,NULL,'http://127.0.0.1:8888/services/redis/createDomain'),
(@TASK_ID,@DETAIL_ID4,5,1,0,NULL,NULL,NULL,NULL,'http://127.0.0.1:8888/services/redis/publishDomain'),
(@TASK_ID,@DETAIL_ID5,6,1,0,NULL,NULL,NULL,NULL,'http://127.0.0.1:8888/services/redis/email');